services:
  - type: web
    name: civictrack-backend
    env: java
    plan: free
    branch: main
    rootDir: backend
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
